substitutions:
  devicename: spore-sensor-ths-sht4x
  friendly_name: Temp and Humidity Sensor SHT4X
  device_description: Detect Temp/Humidity with THS Sensor

esphome:
  name: $devicename
  comment: ${device_description}
  name_add_mac_suffix: true

