WIFI_SSID="your-network-name-here"
WIFI_PASSWORD="your-network-password-here"

# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="your-network-name-here"
CIRCUITPY_WIFI_PASSWORD="your-network-password-here"

# Device Labelling
LOCATION="basement_1"

# PIN Configuration
LED_PIN="IO21"